### ISSUE TITLE
Bug: old link to “Quick tip: ARIA Landmark roles” no longer works

### ISSUE THREAD

**Issue by beep** [a11yproject/a11yproject.com#1049]
## Summary

I recently released a course that links to [Erik Runyon’s excellent “Quick Tip: ARIA Landmark roles and HTML5 implicit mapping”](https://www.a11yproject.com/posts/2013-01-14-aria-landmark-roles/). However, a student emailed to let me know that the URL was 404ing: it looks like it might have been changed in the redesign.

Steps to reproduce:

1. Navigate to https://www.a11yproject.com/posts/aria-landmark-roles.

### Expected result

I’d expect to be redirected to https://www.a11yproject.com/posts/2013-01-14-aria-landmark-roles/.

### Actual result

404 error appears.

**Comment by ericwbailey** [comment]
Oh shoot, that's another link that broke when we moved off GitHub pages. I'll get on adding a redirect ASAP.

**Comment by beep** [comment]
Oh thank you, Eric!

**Comment by ericwbailey** [comment]
I believe this should now be fixed via https://github.com/a11yproject/a11yproject.com/pull/1050. Could I trouble you to confirm? You might have to force refresh/wait 5min for Netlify to do its thing.

**Comment by beep** [comment]
@ericwbailey Hey! I’m still seeing a 404 error here, sadly—hm, actually, I might be seeing a _new_ one? Specifically, this URL:

```
https://www.a11yproject.com/posts/aria-landmark-roles```

is redirecting to this URL:

```
https://www.a11yproject.com/posts/posts/2013-01-14-aria-landmark-roles/```

(That is, there’s an extra `posts` in there.)

I don’t know from Netlify, mind, but is it possible there’s a leading slash missing in https://github.com/a11yproject/a11yproject.com/pull/1050/commits/569de3337357336ff78265c33841dbc824d67ca4#diff-5db06fd2327543bbb72119cd1e5761cfR12?

Thanks so much for looking into this!

**Comment by ericwbailey** [comment]
Yup, nailed it in one with the trailing slash. Sorry about that.

Can you re-verify?

**Comment by beep** [comment]
Verified! Works a treat now. Thanks again, Eric! Really, really appreciate it.

**Comment by ericwbailey** [comment]
Thanks for reporting the issue!
