### ISSUE TITLE
CSS Grid breaks text wrapping for small viewports

### ISSUE THREAD

**Issue by ericwbailey** [a11yproject/a11yproject.com#974]
Issue reported on Twitter:

- https://twitter.com/Aaron_Powell/status/1283808690211033089
- https://twitter.com/jouni_kantola/status/1283894103483318272
- https://twitter.com/michaelfink/status/1283908720246677505

The CSS Grid on the homepage card layouts causes the text to not wrap on smaller screens or zoomed text size. This is an oversight from previous work to remove grid at small sizes.

**Comment by jendowns** [comment]
Hello @ericwbailey I noticed this as well & I believe the fix is related to a margin value on `.c-homepage-card--spotlight` elements:

current|`margin-right` removed
--|--
<img width="797" alt="Screen Shot 2020-07-17 at 12 29 01 PM" src="https://user-images.githubusercontent.com/9057921/87814452-64e27b00-c829-11ea-855f-0f6dc3cce48e.png">|<img width="875" alt="Screen Shot 2020-07-17 at 12 32 16 PM" src="https://user-images.githubusercontent.com/9057921/87814577-9b1ffa80-c829-11ea-9534-d726c5b9826d.png">

**Comment by ericwbailey** [comment]
@jendowns Thank you for that, it was a great starting point. I just pushed up a potential fix, could I trouble you to verify on your end of things? You might have to hard refresh the browser to clear the page cached by the service worker we use.

**Comment by jendowns** [comment]
Hey @ericwbailey, unfortunately I'm still seeing this issue. I also went ahead and ran the updates locally to confirm that the issue still exists at ~375px viewport width (for iPhone 6, 7, 8).

I wanted to revisit the `margin-right` value I mentioned in my previous https://github.com/a11yproject/a11yproject.com/issues/974#issuecomment-660244221, specifically as a way to examine the computed width + margin of `.c-homepage-card--spotlight`.

**I'm seeing the calculated width of the `.c-homepage-card--spotlight` element is 320px, plus it also has a 80px right margin. So that's a total of 400px, which causes it to overflow the 375px viewport.** (Note the circled values in the screenshot below.)


<img width="946" alt="screenshot of .c-homepage-card--spotlight computed width" src="https://user-images.githubusercontent.com/9057921/87956278-779cc000-ca74-11ea-9e38-fb8555efcd61.png">

And you will notice that the computed width of the overflowing text wrapper is exactly 400px:

<img width="952" alt="screenshot of .c-homepage-card computed width" src="https://user-images.githubusercontent.com/9057921/87957308-b67f4580-ca75-11ea-8ed1-6c83e1cc31af.png">


If the `margin-right` value on `.c-homepage-card--spotlight` isn't what you'd like to target with updates, there is a combination of `width` + `margin` values in that element's children that make the computed width of `.c-homepage-card--spotlight` add up to 320px. I was thinking that those are good places to look at. Thank you!

**Comment by ericwbailey** [comment]
Ah, I see! Thank you for the detailed screenshots, and I agree with your call of `c-homepage-card--spotlight` being the culprit. I'll see what I can do 🙏

**Comment by jendowns** [comment]
@ericwbailey No problem! Btw since your updates, I am no longer seeing that text wrapping issue. 🎉 I checked on my iPhone 8 and also checked with Firefox devtools to simulate the ~375px iPhone 6/7/8 screen width. Looks good!

**Comment by ericwbailey** [comment]
Awesome! Thank you for the thorough checks 🎉
